name: NodeJS with Gulp

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g @angular/cli
        npm install
        ng build

    - name: Verify build files
      run: |
        ls -altr
        ls -altr dist
        cat dist/owais-website/index.html
